[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy",
    "Cython",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true

[testenv:tests]
changedir = tests
deps =
    coverage[toml]
    parameterized

commands =
    coverage run -m unittest discover -p "*.py"
    coverage xml

[testenv:examples]
changedir = examples
allowlist_externals = /bin/bash

deps =
    -rexamples/requirements.txt

commands =
    bash -c "export SKCOSMO_EXAMPLES=$PWD; for file in $(find . -name '*.ipynb' -not -path '*/\\.*'); do export filename=$(basename $file); jupyter nbconvert --to notebook --output "$SKCOSMO_EXAMPLES/../.tox/examples/$filename" --execute "$file"; done"
"""

[tool.coverage.run]
branch = true
data_file = 'tests/.coverage'

[tool.coverage.report]
include = [
    "skcosmo/*"
]

[tool.coverage.xml]
output = 'tests/coverage.xml'
