[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv]
changedir = tests
deps =
    coverage[toml]

commands =
    coverage run -m unittest discover -p "*.py"
    coverage xml
"""

[tool.coverage.run]
branch = true
data_file = 'tests/.coverage'

[tool.coverage.report]
include = [
    "skcosmo/*"
]

[tool.coverage.xml]
output = 'tests/coverage.xml'
